### ISSUE TITLE
pdf text bugs

### ISSUE THREAD

**Issue by devops3199** [eazybytes/spring#6]
Hi, thanks for the wonderful spring tutorial.

<img width="453" alt="text" src="https://github.com/eazybytes/spring/assets/8262598/3665d2ff-5198-46da-808c-3660c5214943">

I found an issue on the given pdf. Some words are missing on page 66 and I am not trying to leak anything, but the above snapshot must be provided to raise this issue.

**Comment by eazybytes** [comment]
Thanks @devops3199 for letting me know about this. I fixed the issue & updated the PDF inside the course. Please download the latest PDF and you should be able to see the fix
